Repository googleapis/java-recaptchaenterprise, pull requests merged in 2020-09, with the labels that each got.

#206 build(java): switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: recaptchaenterprise, automerge, cla: yes, context: full

#214 chore: regenerate common templates
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#229 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#231 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: recaptchaenterprise, automerge, cla: yes

#232 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: recaptchaenterprise, automerge, cla: yes, context: full

#237 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#239 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
