Repository googleapis/java-recaptchaenterprise, pull requests merged in 2020-08, with the labels that each got.

#190 cleanup: removes unused kokoro config files
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/integration.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/continuous/samples.cfg
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/lint.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#171 feat: promote to GA
  .repo-metadata.json
  README.md
Labels: cla: yes

#193 chore: regenerate common templates
  .kokoro/dependencies.sh
  README.md
  synth.metadata
Labels: cla: yes, context: partial

#199 chore: regenerate README
  README.md
  synth.metadata
Labels: cla: yes, context: none

#204 samples: add presubmit lint check
  .github/workflows/samples.yaml
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: partial

#205 build: temporarily disable reporting to unblock releases
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: recaptchaenterprise, cla: yes, context: full
