Repository googleapis/java-recaptchaenterprise, pull requests merged in 2021-09, with the labels that each got.

#557 docs(samples): adding README.md
  samples/snippets/cloud-client/src/README.md
Labels: type: docs, cla: yes, api: recaptchaenterprise, samples

#563 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: recaptchaenterprise, automerge

#566 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: kokoro:force-run, cla: yes, api: recaptchaenterprise, automerge

#577 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, api: recaptchaenterprise, automerge

#593 chore: change branch master to main in github configurations
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: recaptchaenterprise, automerge
